name: Build and Release EXE

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4 # v3からv4に更新
    
    - name: Set up Python
      uses: actions/setup-python@v5 # v4からv5に更新
      with:
        python-version: '3.10'
        cache: 'pip' # pipのキャッシュを有効化
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build with PyInstaller
      run: |
        python build_exe.py
        
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/DesktopAI.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
